import { Product } from "./product.interface";

export interface SeedData {
  products: Product[];
}

export const initialData: SeedData = {
  products: [
    // Platos Fuertes
    {
      description: "Delicioso churrasco de res acompañado de papas y ensalada.",
      images: ["Churrasco de Res_1.webp", "Churrasco de Res_2.webp"],
      available: true,
      precio: 25000,
      slug: "churrasco-res",
      tags: ["carne", "parrilla", "res"],
      titulo: "Churrasco de Res",
      seccion: "Platos fuertes",
      tipo: "Comida"
    },
    {
      description: "Pechuga de pollo a la parrilla con arroz y vegetales.",
      images: ["Pechuga de Pollo_1.webp", "Pechuga de Pollo_2.webp"],
      available: true,
      precio: 22000,
      slug: "pechuga-pollo",
      tags: ["pollo", "parrilla", "saludable"],
      titulo: "Pechuga de Pollo",
      seccion: "Platos fuertes",
      tipo: "Comida"
    },
    {
      description: "Deliciosas costillas de cerdo marinadas en una mezcla de especias y hierbas, asadas lentamente hasta alcanzar la perfección. Cada bocado ofrece una explosión de sabores jugosos y tiernos, cubiertas con un glaseado de salsa BBQ que realza su sabor ahumado. Acompañadas de guarniciones irresistibles, perfectas para satisfacer cualquier antojo.",
      images: ["Costillas de Cerdo_1.webp", "Costillas de Cerdo_2.webp"],
      available: true,
      precio: 28000,
      slug: "costillas-cerdo",
      tags: ["cerdo", "parrilla", "costillas"],
      titulo: "Costillas de Cerdo",
      seccion: "Platos fuertes",
      tipo: "Comida"
    },
    {
      description: "Filete de pescado frito con papas fritas y ensalada.",
      images: ["Filete de Pescado Frito_1.webp", "Filete de Pescado Frito_2.webp"],
      available: true,
      precio: 23000,
      slug: "filete-pescado",
      tags: ["pescado", "frito", "mar"],
      titulo: "Filete de Pescado Frito",
      seccion: "Platos fuertes",
      tipo: "Comida"
    },
    {
      description: "Delicioso lomo de cerdo a la parrilla con salsa BBQ.",
      images: ["Lomo de Cerdo BBQ_1.webp", "Lomo de Cerdo BBQ_2.webp"],
      available: true,
      precio: 26000,
      slug: "lomo-cerdo-bbq",
      tags: ["cerdo", "parrilla", "bbq"],
      titulo: "Lomo de Cerdo BBQ",
      seccion: "Platos fuertes",
      tipo: "Comida",
      
      // Opciones de personalización
      customizationOptions: {
        extras: [
          { name: "Salsa BBQ extra", price: 3000 },
          { name: "Papas fritas", price: 4000 },
          { name: "Ensalada", price: 3500 },
          { name: "Porción de arroz", price: 4500 },
          { name: "Porción de patacón", price: 5500 },
        ],
        choices: [
          {
            name: "Término de cocción",
            values: ["Poco hecho", "Al punto", "Bien hecho"],
          },
        ],
      },
    },    
    {
      description:
        "Pasta con salsa boloñesa hecha con carne de res y tomate fresco.",
      images: ["Pasta Boloñesa_1.webp", "Pasta Boloñesa_2.webp"],
      available: true,
      precio: 20000,
      slug: "pasta-bolonesa",
      tags: ["pasta", "res", "italiano"],
      titulo: "Pasta Boloñesa",
      seccion: "Platos fuertes",
      tipo: "Comida"
    },
    {
      description:
        "Chuleta de cerdo empanizada acompañada de ensalada y arroz.",
      images: ["Chuleta Empanizada_1.webp", "Chuleta Empanizada_2.webp"],
      available: true,
      precio: 24000,
      slug: "chuleta-empanizada",
      tags: ["cerdo", "empanizado", "chuleta"],
      titulo: "Chuleta Empanizada",
      seccion: "Platos fuertes",
      tipo: "Comida"
    },
    {
      description: "Pollo a la brasa con papas fritas y ensalada.",
      images: ["Pollo a la Brasa_1.webp", "Pollo a la Brasa_2.webp"],
      available: true,
      precio: 21000,
      slug: "pollo-brasa",
      tags: ["pollo", "brasa", "tradicional"],
      titulo: "Pollo a la Brasa",
      seccion: "Platos fuertes",
      tipo: "Comida"
    },
    {
      description:
        "Delicioso estofado de res cocinado lentamente con papas y zanahorias.",
      images: ["Estofado de Res_1.webp", "Estofado de Res_2.webp"],
      available: true,
      precio: 27000,
      slug: "estofado-res",
      tags: ["res", "estofado", "guiso"],
      titulo: "Estofado de Res",
      seccion: "Platos fuertes",
      tipo: "Comida"
    },
    {
      description: "Camarones al ajillo servidos con arroz y ensalada.",
      images: ["Camarones al Ajillo_1.webp", "Camarones al Ajillo_2.webp"],
      available: true,
      precio: 29000,
      slug: "camarones-ajillo",
      tags: ["mariscos", "camarones", "ajillo"],
      titulo: "Camarones al Ajillo",
      seccion: "Platos fuertes",
      tipo: "Comida"
    },
    // Entradas
    {
      description: "Nachos con queso derretido y salsa guacamole.",
      images: ["Nachos con Guacamole_1.webp", "Nachos con Guacamole_2.webp"],
      available: true,
      precio: 12000,
      slug: "nachos-guacamole",
      tags: ["nachos", "entrada", "queso"],
      titulo: "Nachos con Guacamole",
      seccion: "Entradas",
      tipo: "Entrada"
    },
    {
      description: "Calamares fritos con salsa tártara.",
      images: ["Calamares Fritos_1.webp", "Calamares Fritos_2.webp"],
      available: true,
      precio: 15000,
      slug: "calamares-fritos",
      tags: ["calamares", "entrada", "fritos"],
      titulo: "Calamares Fritos",
      seccion: "Entradas",
      tipo: "Entrada",
    },
    {
      description: "Bruschetta de tomate y albahaca sobre pan crujiente.",
      images: ["Bruschetta de Tomate_1.webp", "Bruschetta de Tomate_2.webp"],
      available: true,
      precio: 10000,
      slug: "bruschetta-tomate",
      tags: ["bruschetta", "entrada", "pan"],
      titulo: "Bruschetta de Tomate",
      seccion: "Entradas",
      tipo: "Entrada",
    },
    {
      description: "Tacos pequeños de carne con cebolla y cilantro.",
      images: ["Tacos de Carne_1.webp", "Tacos de Carne_2.webp"],
      available: true,
      precio: 14000,
      slug: "tacos-carne",
      tags: ["tacos", "entrada", "carne"],
      titulo: "Tacos de Carne",
      seccion: "Entradas",
      tipo: "Entrada",
    },
    {
      description: "Queso fundido con chorizo y tortillas de maíz.",
      images: ["Queso Fundido con Chorizo_1.webp", "Queso Fundido con Chorizo_2.webp"],
      available: true,
      precio: 13000,
      slug: "queso-fundido",
      tags: ["queso", "entrada", "chorizo"],
      titulo: "Queso Fundido con Chorizo",
      seccion: "Entradas",
      tipo: "Entrada",
    },
    {
      description: "Alitas de pollo con salsa búfalo picante.",
      images: ["Alitas Búfalo_1.webp", "Alitas Búfalo_2.webp"],
      available: true,
      precio: 16000,
      slug: "alitas-bufalo",
      tags: ["alitas", "entrada", "picante"],
      titulo: "Alitas Búfalo",
      seccion: "Entradas",
      tipo: "Entrada",
    },
    {
      description: "Rollitos de primavera rellenos de vegetales y pollo.",
      images: ["Rollitos de Primavera_1.webp", "Rollitos de Primavera_2.webp"],
      available: true,
      precio: 11000,
      slug: "rollitos-primavera",
      tags: ["rollitos", "entrada", "vegetales"],
      titulo: "Rollitos de Primavera",
      seccion: "Entradas",
      tipo: "Entrada",
    },
    {
      description: "Empanadas de carne con chimichurri.",
      images: ["Empanadas de Carne_1.webp", "Empanadas de Carne_2.webp"],
      available: true,
      precio: 12000,
      slug: "empanadas-carne",
      tags: ["empanadas", "entrada", "carne"],
      titulo: "Empanadas de Carne",
      seccion: "Entradas",
      tipo: "Entrada",
    },
    {
      description: "Ceviche de camarón con limón y cilantro.",
      images: ["Ceviche de Camarón_1.webp", "Ceviche de Camarón_2.webp"],
      available: true,
      precio: 17000,
      slug: "ceviche-camaron",
      tags: ["ceviche", "entrada", "mariscos"],
      titulo: "Ceviche de Camarón",
      seccion: "Entradas",
      tipo: "Entrada",
    },
    {
      description: "Hummus de garbanzos con pan pita.",
      images: ["Hummus con Pan Pita_1.webp", "Hummus con Pan Pita_2.webp"],
      available: true,
      precio: 9000,
      slug: "hummus-garbanzos",
      tags: ["hummus", "entrada", "vegetariano"],
      titulo: "Hummus con Pan Pita",
      seccion: "Entradas",
      tipo: "Entrada",
    },

    // Hamburguesas
    {
      description: "Hamburguesa clásica con queso, lechuga, y tomate.",
      images: ["Hamburguesa Clásica_1.webp", "Hamburguesa Clásica_2.webp"],
      available: true,
      precio: 18000,
      slug: "hamburguesa-clasica",
      tags: ["hamburguesa", "queso", "clásico"],
      titulo: "Hamburguesa Clásica",
      seccion: "Hamburguesas",
      tipo: "Comida",
    },
    {
      description: "Hamburguesa con doble carne, queso cheddar y tocino.",
      images: ["Hamburguesa Doble_1.webp", "Hamburguesa Doble_2.webp"],
      available: true,
      precio: 22000,
      slug: "hamburguesa-doble",
      tags: ["hamburguesa", "doble carne", "tocino"],
      titulo: "Hamburguesa Doble",
      seccion: "Hamburguesas",
      tipo: "Comida",
    },
    {
      description: "Hamburguesa vegetariana con queso de cabra y espinacas.",
      images: ["Hamburguesa Vegetariana_1.webp", "Hamburguesa Vegetariana_2.webp"],
      available: true,
      precio: 20000,
      slug: "hamburguesa-vegetariana",
      tags: ["vegetariana", "hamburguesa", "espinacas"],
      titulo: "Hamburguesa Vegetariana",
      seccion: "Hamburguesas",
      tipo: "Comida",
    },
    {
      description: "Hamburguesa de pollo crujiente con mayonesa y lechuga.",
      images: ["Hamburguesa de Pollo_1.webp", "Hamburguesa de Pollo_2.webp"],
      available: true,
      precio: 19000,
      slug: "hamburguesa-pollo",
      tags: ["pollo", "crujiente", "hamburguesa"],
      titulo: "Hamburguesa de Pollo",
      seccion: "Hamburguesas",
      tipo: "Comida",
    },
    {
      description: "Hamburguesa con guacamole, jalapeños y queso suizo.",
      images: ["Hamburguesa con Guacamole_1.webp", "Hamburguesa con Guacamole_2.webp"],
      available: true,
      precio: 21000,
      slug: "hamburguesa-guacamole",
      tags: ["guacamole", "jalapeños", "hamburguesa"],
      titulo: "Hamburguesa con Guacamole",
      seccion: "Hamburguesas",
      tipo: "Comida",
    },
    {
      description:
        "Hamburguesa con queso azul, cebolla caramelizada y champiñones.",
      images: ["Hamburguesa con Queso Azul_1.webp", "Hamburguesa con Queso Azul_2.webp"],
      available: true,
      precio: 23000,
      slug: "hamburguesa-queso-azul",
      tags: ["queso azul", "cebolla caramelizada", "hamburguesa"],
      titulo: "Hamburguesa con Queso Azul",
      seccion: "Hamburguesas",
      tipo: "Comida",
    },
    {
      description: "Hamburguesa con huevo frito, jamón y salsa de mostaza.",
      images: ["Hamburguesa con Huevo Frito_1.webp", "Hamburguesa con Huevo Frito_2.webp"],
      available: true,
      precio: 22000,
      slug: "hamburguesa-huevo-frito",
      tags: ["huevo frito", "jamón", "hamburguesa"],
      titulo: "Hamburguesa con Huevo Frito",
      seccion: "Hamburguesas",
      tipo: "Comida",
    },
    {
      description: "Hamburguesa BBQ con aros de cebolla y queso cheddar.",
      images: ["Hamburguesa BBQ_1.webp", "Hamburguesa BBQ_2.webp"],
      available: true,
      precio: 24000,
      slug: "hamburguesa-bbq",
      tags: ["bbq", "aros de cebolla", "hamburguesa"],
      titulo: "Hamburguesa BBQ",
      seccion: "Hamburguesas",
      tipo: "Comida",
    },
    {
      description: "Hamburguesa con aguacate, tomate y queso feta.",
      images: ["Hamburguesa con Aguacate_1.webp", "Hamburguesa con Aguacate_2.webp"],
      available: true,
      precio: 21000,
      slug: "hamburguesa-aguacate",
      tags: ["aguacate", "queso feta", "hamburguesa"],
      titulo: "Hamburguesa con Aguacate",
      seccion: "Hamburguesas",
      tipo: "Comida",
    },
    {
      description: "Hamburguesa picante con salsa sriracha y jalapeños.",
      images: ["Hamburguesa Sriracha_1.webp", "Hamburguesa Sriracha_2.webp"],
      available: true,
      precio: 22000,
      slug: "hamburguesa-sriracha",
      tags: ["picante", "sriracha", "hamburguesa"],
      titulo: "Hamburguesa Sriracha",
      seccion: "Hamburguesas",
      tipo: "Comida",
    },

    // Perros Calientes
    {
      description:
        "Perro caliente con salchicha, cebolla caramelizada y salsa BBQ.",
      images: ["Perro Caliente BBQ_1.webp", "Perro Caliente BBQ_2.webp"],
      available: true,
      precio: 15000,
      slug: "perro-bbq",
      tags: ["perro caliente", "salchicha", "bbq"],
      titulo: "Perro Caliente BBQ",
      seccion: "Perros calientes",
      tipo: "Comida",
    },
    {
      description: "Perro caliente con salchicha alemana y mostaza dijon.",
      images: ["Perro Caliente Alemán_1.webp", "Perro Caliente Alemán_2.webp"],
      available: true,
      precio: 16000,
      slug: "perro-aleman",
      tags: ["perro caliente", "alemán", "mostaza"],
      titulo: "Perro Caliente Alemán",
      seccion: "Perros calientes",
      tipo: "Comida",
    },
    {
      description:
        "Perro caliente con salchicha, queso cheddar derretido y tocino.",
      images: ["Perro Caliente con Queso Cheddar y Tocino_1.webp", "Perro Caliente con Queso Cheddar y Tocino_2.webp"],
      available: true,
      precio: 17000,
      slug: "perro-cheddar-tocino",
      tags: ["perro caliente", "tocino", "queso cheddar"],
      titulo: "Perro Caliente con Queso Cheddar y Tocino",
      seccion: "Perros calientes",
      tipo: "Comida",
    },
    {
      description: "Perro caliente con salchicha, guacamole y jalapeños.",
      images: ["Perro Caliente con Guacamole y Jalapeños_1.webp", "Perro Caliente con Guacamole y Jalapeños_2.webp"],
      available: true,
      precio: 18000,
      slug: "perro-guacamole-jalapeno",
      tags: ["perro caliente", "guacamole", "jalapeños"],
      titulo: "Perro Caliente con Guacamole y Jalapeños",
      seccion: "Perros calientes",
      tipo: "Comida",
    },
    {
      description: "Perro caliente con salchicha de pollo, lechuga y mayonesa.",
      images: ["Perro Caliente de Pollo con Lechuga_1.webp", "Perro Caliente de Pollo con Lechuga_2.webp"],
      available: true,
      precio: 16000,
      slug: "perro-pollo-lechuga",
      tags: ["perro caliente", "salchicha de pollo", "mayonesa"],
      titulo: "Perro Caliente de Pollo con Lechuga",
      seccion: "Perros calientes",
      tipo: "Comida",
    },
    {
      description: "Perro caliente con salchicha italiana y pimientos asados.",
      images: ["Perro Caliente Italiano con Pimientos_1.webp", "Perro Caliente Italiano con Pimientos_2.webp"],
      available: true,
      precio: 19000,
      slug: "perro-italiano-pimientos",
      tags: ["perro caliente", "italiano", "pimientos"],
      titulo: "Perro Caliente Italiano con Pimientos",
      seccion: "Perros calientes",
      tipo: "Comida",
    },
    {
      description: "Perro caliente con salchicha de cerdo, chucrut y mostaza.",
      images: ["Perro Caliente de Cerdo con Chucrut_1", "Perro Caliente de Cerdo con Chucrut_2.webp"],
      available: true,
      precio: 18000,
      slug: "perro-cerdo-chucrut",
      tags: ["perro caliente", "salchicha de cerdo", "chucrut"],
      titulo: "Perro Caliente de Cerdo con Chucrut",
      seccion: "Perros calientes",
      tipo: "Comida",
    },
    {
      description:
        "Perro caliente vegetariano con salchicha de tofu y salsa de tomate.",
      images: ["Perro Caliente Vegetariano_1.webp", "Perro Caliente Vegetariano_2.webp"],
      available: true,
      precio: 15000,
      slug: "perro-vegetariano-tofu",
      tags: ["perro caliente", "vegetariano", "tofu"],
      titulo: "Perro Caliente Vegetariano",
      seccion: "Perros calientes",
      tipo: "Comida",
    },
    {
      description: "Perro caliente con salchicha picante y salsa de ají.",
      images: ["Perro Caliente Picante con Ají_1.webp", "Perro Caliente Picante con Ají_2.webp"],
      available: true,
      precio: 17000,
      slug: "perro-picante-aji",
      tags: ["perro caliente", "picante", "ají"],
      titulo: "Perro Caliente Picante con Ají",
      seccion: "Perros calientes",
      tipo: "Comida",
    },
    {
      description:
        "Perro caliente con salchicha, queso azul y cebolla crujiente.",
      images: ["Perro Caliente con Queso Azul_1.webp", "Perro Caliente con Queso Azul_2.webp"],
      available: true,
      precio: 20000,
      slug: "perro-queso-azul",
      tags: ["perro caliente", "queso azul", "cebolla crujiente"],
      titulo: "Perro Caliente con Queso Azul",
      seccion: "Perros calientes",
      tipo: "Comida",
    },

    // Cervezas
    {
      description: "Cerveza artesanal IPA con sabor cítrico.",
      images: ["Cerveza IPA_1.webp", "Cerveza IPA_2.webp"],
      available: true,
      precio: 12000,
      slug: "cerveza-ipa",
      tags: ["cerveza", "ipa", "artesanal"],
      titulo: "Cerveza IPA",
      seccion: "Cervezas",
      tipo: "Bebidas",
    },
    {
      description: "Cerveza rubia ligera y refrescante.",
      images: ["Cerveza Rubia_1.webp", "Cerveza Rubia_2.webp"],
      available: true,
      precio: 11000,
      slug: "cerveza-rubia",
      tags: ["cerveza", "rubia", "ligera"],
      titulo: "Cerveza Rubia",
      seccion: "Cervezas",
      tipo: "Bebidas",
    },
    {
      description: "Cerveza oscura con notas de chocolate y café.",
      images: ["Cerveza Oscura_1.webp", "Cerveza Oscura_2.webp"],
      available: true,
      precio: 13000,
      slug: "cerveza-oscura",
      tags: ["cerveza", "oscura", "chocolate"],
      titulo: "Cerveza Oscura",
      seccion: "Cervezas",
      tipo: "Bebidas",
    },
    {
      description: "Cerveza de trigo suave con un toque de naranja.",
      images: ["Cerveza de Trigo_1.webp", "Cerveza de Trigo_2.webp"],
      available: true,
      precio: 12000,
      slug: "cerveza-trigo",
      tags: ["cerveza", "trigo", "naranja"],
      titulo: "Cerveza de Trigo",
      seccion: "Cervezas",
      tipo: "Bebidas",
    },
    {
      description: "Cerveza lager clásica de sabor equilibrado.",
      images: ["Cerveza Lager_1.webp", "Cerveza Lager_2.webp"],
      available: true,
      precio: 11500,
      slug: "cerveza-lager",
      tags: ["cerveza", "lager", "clásica"],
      titulo: "Cerveza Lager",
      seccion: "Cervezas",
      tipo: "Bebidas",
    },
    {
      description: "Cerveza roja con un toque de caramelo.",
      images: ["Cerveza Roja_1.webp", "Cerveza Roja_2.webp"],
      available: true,
      precio: 12500,
      slug: "cerveza-roja",
      tags: ["cerveza", "roja", "caramelo"],
      titulo: "Cerveza Roja",
      seccion: "Cervezas",
      tipo: "Bebidas",
    },
    {
      description: "Cerveza negra fuerte con notas de malta tostada.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 14000,
      slug: "cerveza-negra",
      tags: ["cerveza", "negra", "malta"],
      titulo: "Cerveza Negra",
      seccion: "Cervezas",
      tipo: "Bebidas",
    },
    {
      description: "Cerveza artesanal pale ale con aroma a lúpulo fresco.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 13000,
      slug: "cerveza-pale-ale",
      tags: ["cerveza", "pale ale", "lúpulo"],
      titulo: "Cerveza Pale Ale",
      seccion: "Cervezas",
      tipo: "Bebidas",
    },
    {
      description: "Cerveza belga de abadía con sabor afrutado.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 15000,
      slug: "cerveza-belga",
      tags: ["cerveza", "belga", "afrutado"],
      titulo: "Cerveza Belga de Abadía",
      seccion: "Cervezas",
      tipo: "Bebidas",
    },
    {
      description: "Cerveza pilsner refrescante con un toque amargo.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 11000,
      slug: "cerveza-pilsner",
      tags: ["cerveza", "pilsner", "refrescante"],
      titulo: "Cerveza Pilsner",
      seccion: "Cervezas",
      tipo: "Bebidas",
    },

    // Bebidas Calientes
    {
      description: "Café espresso fuerte y aromático.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 8000,
      slug: "cafe-espresso",
      tags: ["café", "espresso", "bebida caliente"],
      titulo: "Café Espresso",
      seccion: "Bebidas calientes",
      tipo: "Bebidas",
    },
    {
      description: "Té verde antioxidante servido caliente.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 7000,
      slug: "te-verde",
      tags: ["té", "verde", "bebida caliente"],
      titulo: "Té Verde",
      seccion: "Bebidas calientes",
      tipo: "Bebidas",
    },
    {
      description: "Chocolate caliente cremoso con un toque de canela.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 9000,
      slug: "chocolate-caliente",
      tags: ["chocolate", "canela", "bebida caliente"],
      titulo: "Chocolate Caliente",
      seccion: "Bebidas calientes",
      tipo: "Bebidas",
    },
    {
      description: "Capuchino con espuma de leche y cacao espolvoreado.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 8500,
      slug: "capuchino",
      tags: ["capuchino", "café", "bebida caliente"],
      titulo: "Capuchino",
      seccion: "Bebidas calientes",
      tipo: "Bebidas",
    },
    {
      description: "Té chai especiado con leche caliente.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 8000,
      slug: "te-chai",
      tags: ["té", "chai", "bebida caliente"],
      titulo: "Té Chai",
      seccion: "Bebidas calientes",
      tipo: "Bebidas",
    },
    {
      description: "Latte con leche espumosa y un shot de espresso.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 9000,
      slug: "latte",
      tags: ["latte", "café", "bebida caliente"],
      titulo: "Café Latte",
      seccion: "Bebidas calientes",
      tipo: "Bebidas",
    },
    {
      description: "Infusión de manzanilla calmante servida caliente.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 7000,
      slug: "infusion-manzanilla",
      tags: ["manzanilla", "infusión", "bebida caliente"],
      titulo: "Infusión de Manzanilla",
      seccion: "Bebidas calientes",
      tipo: "Bebidas",
    },
    {
      description: "Café americano suave y equilibrado.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 8000,
      slug: "cafe-americano",
      tags: ["café", "americano", "bebida caliente"],
      titulo: "Café Americano",
      seccion: "Bebidas calientes",
      tipo: "Bebidas",
    },
    {
      description: "Té negro fuerte con un toque de limón.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 7500,
      slug: "te-negro",
      tags: ["té", "negro", "bebida caliente"],
      titulo: "Té Negro con Limón",
      seccion: "Bebidas calientes",
      tipo: "Bebidas",
    },
    {
      description: "Café mocha con chocolate y crema batida.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 9500,
      slug: "cafe-mocha",
      tags: ["mocha", "chocolate", "bebida caliente"],
      titulo: "Café Mocha",
      seccion: "Bebidas calientes",
      tipo: "Bebidas",
    },
    //Pizzas
    {
      description: "Pizza margarita clásica con salsa de tomate y albahaca.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 22000,
      slug: "pizza-margarita",
      tags: ["pizza", "margarita", "clásica"],
      titulo: "Pizza Margarita",
      seccion: "Pizza",
      tipo: "Comida",
    },
    {
      description: "Pizza de pepperoni con extra queso mozzarella.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 24000,
      slug: "pizza-pepperoni",
      tags: ["pizza", "pepperoni", "queso"],
      titulo: "Pizza de Pepperoni",
      seccion: "Pizza",
      tipo: "Comida",
    },
    {
      description: "Pizza vegetariana con champiñones, pimientos y aceitunas.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 23000,
      slug: "pizza-vegetariana",
      tags: ["pizza", "vegetariana", "champiñones"],
      titulo: "Pizza Vegetariana",
      seccion: "Pizza",
      tipo: "Comida",
    },
    {
      description:
        "Pizza cuatro quesos con mozzarella, parmesano, gorgonzola y ricotta.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 25000,
      slug: "pizza-cuatro-quesos",
      tags: ["pizza", "cuatro quesos", "queso"],
      titulo: "Pizza Cuatro Quesos",
      seccion: "Pizza",
      tipo: "Comida",
    },
    {
      description: "Pizza hawaiana con piña, jamón y queso mozzarella.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 24000,
      slug: "pizza-hawaiana",
      tags: ["pizza", "hawaiana", "piña"],
      titulo: "Pizza Hawaiana",
      seccion: "Pizza",
      tipo: "Comida",
    },
    {
      description: "Pizza BBQ con pollo a la parrilla y salsa barbacoa.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 26000,
      slug: "pizza-bbq",
      tags: ["pizza", "pollo", "bbq"],
      titulo: "Pizza BBQ de Pollo",
      seccion: "Pizza",
      tipo: "Comida",
    },
    {
      description: "Pizza de jamón serrano con rúcula y queso parmesano.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 27000,
      slug: "pizza-jamon-serrano",
      tags: ["pizza", "jamón serrano", "rúcula"],
      titulo: "Pizza de Jamón Serrano",
      seccion: "Pizza",
      tipo: "Comida",
    },
    {
      description: "Pizza de atún con cebolla morada y alcaparras.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 25000,
      slug: "pizza-atun",
      tags: ["pizza", "atún", "alcaparras"],
      titulo: "Pizza de Atún",
      seccion: "Pizza",
      tipo: "Comida",
    },
    {
      description: "Pizza mexicana con carne molida, jalapeños y frijoles.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 26000,
      slug: "pizza-mexicana",
      tags: ["pizza", "mexicana", "jalapeños"],
      titulo: "Pizza Mexicana",
      seccion: "Pizza",
      tipo: "Comida",
    },
    {
      description: "Pizza con jamón, champiñones y queso mozzarella.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 23000,
      slug: "pizza-jamon-champinones",
      tags: ["pizza", "jamón", "champiñones"],
      titulo: "Pizza de Jamón y Champiñones",
      seccion: "Pizza",
      tipo: "Comida",
    },
    // Cocteles
    {
      description: "Mojito clásico con ron, hierbabuena y limón.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 18000,
      slug: "mojito-clasico",
      tags: ["coctel", "mojito", "ron"],
      titulo: "Mojito Clásico",
      seccion: "Cocteles",
      tipo: "Bebidas",
    },
    {
      description: "Piña colada con ron, crema de coco y piña natural.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 20000,
      slug: "pina-colada",
      tags: ["coctel", "piña colada", "ron"],
      titulo: "Piña Colada",
      seccion: "Cocteles",
      tipo: "Bebidas",
    },
    {
      description: "Margarita clásica con tequila, limón y sal en el borde.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 19000,
      slug: "margarita-clasica",
      tags: ["coctel", "margarita", "tequila"],
      titulo: "Margarita Clásica",
      seccion: "Cocteles",
      tipo: "Bebidas",
    },
    {
      description: "Caipirinha brasileña con cachaça, lima y azúcar.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 18000,
      slug: "caipirinha",
      tags: ["coctel", "caipirinha", "cachaça"],
      titulo: "Caipirinha",
      seccion: "Cocteles",
      tipo: "Bebidas",
    },
    {
      description: "Daiquiri de fresa con ron, jugo de fresa y limón.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 20000,
      slug: "daiquiri-fresa",
      tags: ["coctel", "daiquiri", "fresa"],
      titulo: "Daiquiri de Fresa",
      seccion: "Cocteles",
      tipo: "Bebidas",
    },
    {
      description: "Tequila sunrise con tequila, jugo de naranja y granadina.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 19000,
      slug: "tequila-sunrise",
      tags: ["coctel", "tequila", "naranja"],
      titulo: "Tequila Sunrise",
      seccion: "Cocteles",
      tipo: "Bebidas",
    },
    {
      description: "Negroni con ginebra, vermut rojo y campari.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 21000,
      slug: "negroni",
      tags: ["coctel", "negroni", "ginebra"],
      titulo: "Negroni",
      seccion: "Cocteles",
      tipo: "Bebidas",
    },
    {
      description:
        "Cosmopolitan con vodka, jugo de arándano y licor de naranja.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 20000,
      slug: "cosmopolitan",
      tags: ["coctel", "cosmopolitan", "vodka"],
      titulo: "Cosmopolitan",
      seccion: "Cocteles",
      tipo: "Bebidas",
    },
    {
      description:
        "Bloody Mary con vodka, jugo de tomate, limón y salsa picante.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 19000,
      slug: "bloody-mary",
      tags: ["coctel", "bloody mary", "vodka"],
      titulo: "Bloody Mary",
      seccion: "Cocteles",
      tipo: "Bebidas",
    },
    {
      description: "Mai Tai con ron, jugo de piña y curaçao.",
      images: ["hamburguesa.webp", "churrasco.webp"],
      available: true,
      precio: 21000,
      slug: "mai-tai",
      tags: ["coctel", "mai tai", "ron"],
      titulo: "Mai Tai",
      seccion: "Cocteles",
      tipo: "Bebidas",
    },
  ],
};
